### ISSUE TITLE
Boyer–Moore string-search algorithm

### ISSUE THREAD

**Issue by moeryomenko** [Gravonere/learn-algorithms#1]
I look forward to the [Boyer-Moore algorithm](https://en.wikipedia.org/wiki/Boyer%E2%80%93Moore_string-search_algorithm) for finding a substring in a string, with a detailed description of how it works

**Comment by s-a-ovodkov** [comment]
@moeryomenko Later. In the beginning, the standard algorithms.

**Comment by moeryomenko** [comment]
> @moeryomenko Later. In the beginning, the standard algorithms.

I'll wait
